# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'hrmph_shows' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	
	pod 'RxSwift', '5.1.0'
	pod 'RxCocoa', '5.1.0'
	pod 'Kingfisher', '~> 5.1'
  	pod 'iCarousel', '~> 1.8'
  	pod 'SwiftVideoBackground'

  end
